export const colors = {
  white: 'white',
  black: 'black',
  purple: 'purple',
  grey: 'grey',
  blue: 'blue',
  gold: 'gold',
  green: 'green',
  red: 'red',
  pink: 'pink',
};

export const countries = {
  usa: 'USA',
  korea: 'Korea',
  china: 'China',
  japan: 'Japan',
};

export const OS = {
  android: 'Android',
  ios: 'iOS',
};

export const goods = [
  {
    brand: 'Samsung',
    model: 'Galaxy M52',
    memory: 128,
    price: 12999,
    haveDiscount: true,
    isStoredInFacility: true,
    color: colors.white,
    country: countries.korea,
    os: OS.android,
    photo: 'https://content.rozetka.com.ua/goods/images/big/225753307.jpg',
  },
  {
    brand: 'Apple',
    model: 'iPhone 11',
    memory: 64,
    price: 19999,
    haveDiscount: false,
    isStoredInFacility: true,
    color: colors.purple,
    country: countries.usa,
    os: OS.ios,
    photo: 'https://content2.rozetka.com.ua/goods/images/big/37393876.jpg',
  },
  {
    brand: 'Xiaomi',
    model: 'Redmi Note 10S',
    memory: 64,
    price: 8999,
    haveDiscount: true,
    isStoredInFacility: true,
    color: colors.grey,
    country: countries.china,
    os: OS.android,
    photo: 'https://content1.rozetka.com.ua/goods/images/big/179450853.jpg',
  },
  {
    brand: 'Apple',
    model: 'iPhone 13',
    memory: 256,
    price: 33999,
    haveDiscount: false,
    isStoredInFacility: true,
    color: colors.red,
    country: countries.usa,
    os: OS.ios,
    photo: 'https://content2.rozetka.com.ua/goods/images/big/221212843.jpg',
  },
  {
    brand: 'Samsung',
    model: 'Galaxy A52',
    memory: 128,
    price: 10999,
    haveDiscount: true,
    isStoredInFacility: false,
    color: colors.blue,
    country: countries.korea,
    os: OS.android,
    photo: 'https://content2.rozetka.com.ua/goods/images/big/166279502.jpg',
  },
  {
    brand: 'Apple',
    model: 'iPhone 13 mini',
    memory: 512,
    price: 35999,
    haveDiscount: true,
    isStoredInFacility: true,
    color: colors.green,
    country: countries.usa,
    os: OS.ios,
    photo: 'https://content2.rozetka.com.ua/goods/images/big/221273383.jpg',
  },
  {
    brand: 'Xiaomi',
    model: 'Redmi Note 11',
    memory: 128,
    price: 8499,
    haveDiscount: false,
    isStoredInFacility: false,
    color: colors.grey,
    country: countries.china,
    os: OS.android,
    photo: 'https://content.rozetka.com.ua/goods/images/big/250762458.jpg',
  },
  {
    brand: 'Samsung',
    model: 'Galaxy M12',
    memory: 64,
    price: 6499,
    haveDiscount: true,
    isStoredInFacility: true,
    color: colors.white,
    country: countries.korea,
    os: OS.android,
    photo: 'https://content1.rozetka.com.ua/goods/images/big/175471717.jpg',
  },
  {
    brand: 'Samsung',
    model: 'Galaxy A32',
    memory: 128,
    price: 9499,
    haveDiscount: true,
    isStoredInFacility: true,
    color: colors.purple,
    country: countries.korea,
    os: OS.android,
    photo: 'https://content1.rozetka.com.ua/goods/images/big/165917377.jpg',
  },
  {
    brand: 'Samsung',
    model: 'Galaxy M52',
    memory: 128,
    price: 12999,
    haveDiscount: true,
    isStoredInFacility: true,
    color: colors.green,
    country: countries.korea,
    os: OS.android,
    photo: 'https://content.rozetka.com.ua/goods/images/big/225753307.jpg',
  },
  {
    brand: 'Apple',
    model: 'iPhone 13 Pro Max',
    memory: 128,
    price: 43999,
    haveDiscount: true,
    isStoredInFacility: true,
    color: colors.gold,
    country: countries.usa,
    os: OS.ios,
    photo: 'https://content2.rozetka.com.ua/goods/images/big/221216158.jpg',
  },
  {
    brand: 'Apple',
    model: 'iPhone 12',
    memory: 64,
    price: 24999,
    haveDiscount: false,
    isStoredInFacility: true,
    color: colors.green,
    country: countries.usa,
    os: OS.ios,
    photo: 'https://content.rozetka.com.ua/goods/images/big/173867780.jpg',
  },
  {
    brand: 'Sony',
    model: 'Xperia 1 III',
    memory: 512,
    price: 39999,
    haveDiscount: false,
    isStoredInFacility: true,
    color: colors.black,
    country: countries.japan,
    os: OS.android,
    photo: 'https://content1.rozetka.com.ua/goods/images/big/215587054.jpg',
  },
  {
    brand: 'Sony',
    model: 'Xperia 1 III',
    memory: 512,
    price: 39999,
    haveDiscount: false,
    isStoredInFacility: true,
    color: colors.gold,
    country: countries.japan,
    os: OS.android,
    photo: 'https://content1.rozetka.com.ua/goods/images/big/215587054.jpg',
  },
  {
    brand: 'Apple',
    model: 'iPhone 12',
    memory: 64,
    price: 24999,
    haveDiscount: false,
    isStoredInFacility: true,
    color: colors.purple,
    country: countries.usa,
    os: OS.ios,
    photo: 'https://content.rozetka.com.ua/goods/images/big/173867780.jpg',
  },
  {
    brand: 'Samsung',
    model: 'Galaxy M12',
    memory: 64,
    price: 6499,
    haveDiscount: true,
    isStoredInFacility: true,
    color: colors.black,
    country: countries.korea,
    os: OS.android,
    photo: 'https://content1.rozetka.com.ua/goods/images/big/175471717.jpg',
  },
  {
    brand: 'Motorola',
    model: 'Moto G60',
    memory: 128,
    price: 8999,
    haveDiscount: true,
    isStoredInFacility: true,
    color: colors.grey,
    country: countries.usa,
    os: OS.android,
    photo: 'https://content2.rozetka.com.ua/goods/images/big/220713124.jpg',
  },
  {
    brand: 'Apple',
    model: 'iPhone 13 mini',
    memory: 512,
    price: 35999,
    haveDiscount: true,
    isStoredInFacility: true,
    color: colors.red,
    country: countries.usa,
    os: OS.ios,
    photo: 'https://content2.rozetka.com.ua/goods/images/big/221273383.jpg',
  },
  {
    brand: 'Apple',
    model: 'iPhone 13',
    memory: 256,
    price: 33999,
    haveDiscount: false,
    isStoredInFacility: true,
    color: colors.black,
    country: countries.usa,
    os: OS.ios,
    photo: 'https://content2.rozetka.com.ua/goods/images/big/221212843.jpg',
  },
  {
    brand: 'Apple',
    model: 'iPhone 12',
    memory: 128,
    price: 27999,
    haveDiscount: false,
    isStoredInFacility: true,
    color: colors.purple,
    country: countries.usa,
    os: OS.ios,
    photo: 'https://content.rozetka.com.ua/goods/images/big/175435401.jpg',
  },
  {
    brand: 'Apple',
    model: 'iPhone 13',
    memory: 128,
    price: 29999,
    haveDiscount: false,
    isStoredInFacility: true,
    color: colors.pink,
    country: countries.usa,
    os: OS.ios,
    photo: 'https://content.rozetka.com.ua/goods/images/big/221214152.jpg',
  },
  {
    brand: 'Apple',
    model: 'iPhone 13 mini',
    memory: 128,
    price: 25999,
    haveDiscount: true,
    isStoredInFacility: true,
    color: colors.pink,
    country: countries.usa,
    os: OS.ios,
    photo: 'https://content2.rozetka.com.ua/goods/images/big/221268401.jpg',
  },
  {
    brand: 'Apple',
    model: 'iPhone 13 Pro Max',
    memory: 256,
    price: 48999,
    haveDiscount: false,
    isStoredInFacility: true,
    color: colors.gold,
    country: countries.usa,
    os: OS.ios,
    photo: 'https://content2.rozetka.com.ua/goods/images/big/221268401.jpg',
  },
];
